name: Provision S3
on:
  push:
    branches:
      - 'feature/*'

jobs:
  checkout_code:
    name: Checkout source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

  tf_plan:
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/setup-node@v3
#        with:
#          node-version: '14'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.AWS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_KEY }}'
          aws-region: us-east-2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.3
      - name: Terraform Plan
        run: |
          cd tf/
          terraform init
          terraform validate
          terraform plan -out=terraform.plan
  tf_apply:
    runs-on: ubuntu-latest
    needs: [checkout_code, tf_plan]
    steps:
      - name: Apply Terraform code
        run: terraform apply -auto-approve terraform.plan
